User stats
Consdata/clbox pull request #45
Opened 2020-09-30 14:57 UTC by martini449

2020-10-07 10:55 UTC, glipecki requested changes
a gdzie będą teraz statystyki firmowe? zróbmy w tej prce zbieranie w bazie a prezentację zrobimy w osobnej ok?

2020-10-07 10:55 UTC, glipecki commented on apps/functions/src/app/user-feedback-stats-factory.ts
> +              [day]: (statsData?.byYear?.[year]?.[day] ?? 0) + 1,
co powiesz na field.inc?

2020-10-07 15:09 UTC, martini449 commented on apps/functions/src/app/user-feedback-stats-factory.ts
> +              [day]: (statsData?.byYear?.[year]?.[day] ?? 0) + 1,
spróbuję

2020-10-08 06:49 UTC, glipecki commented
Jeszcze się zastanawiam jakby mogła wyglądać ta struktura żeby w przyszłości uwzględnić zarówno wysłane, jak i otrzymane feedbacki w statystykach. Konkretniej, pole stats będzie za krótki bo a. ma zbyt ogólną nazwę, b. czy to powinno być pole? ;-)

2020-10-14 10:38 UTC, martini449 commented
> Jeszcze się zastanawiam jakby mogła wyglądać ta struktura żeby w przyszłości uwzględnić zarówno wysłane, jak i otrzymane feedbacki w statystykach. Konkretniej, pole stats będzie za krótki bo a. ma zbyt ogólną nazwę, b. czy to powinno być pole? ;-)

nie mam pomysłu jak to zrobić inaczej na razie

2020-10-14 11:03 UTC, martini449 commented
> a gdzie będą teraz statystyki firmowe? zróbmy w tej prce zbieranie w bazie a prezentację zrobimy w osobnej ok?

wywaliłem zmiany z widoku

2020-10-14 13:59 UTC, glipecki approved these changes

2020-10-14 13:59 UTC, glipecki commented on packages/firestore/firestore.rules
> +    // read team info for chapter leader
wywalmy jeszcze reguły bo chwilowo nie są potrzebne i lećmy z merge!

2020-10-15 07:19 UTC, merged